### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by cookeyhills** [weezyval/state-LGA-NG#1]
Great job! I found this extremely useful. Some minor bugs fixed:

1. Error in Rivers State listing. LGAs of Enugu displayed. 
2. Abuja changed to FCT. 
3. Alphabtical listing of states corrected. 
4. Duplicate states removed.
5. Error in Nasarawa listing. Wrong LGAs displayed.

**Comment by ekpangmichael** [comment]
I'm glad you find this useful. This has been fixed.

**Comment by amjedidiah** [comment]
Very helpful stuff @ekpangmichael 
Made a pull request due to some difficulties I encountered while using it with Apple devices
Do take a look

**Comment by ekpangmichael** [comment]
Thanks a lot @amjedidiah. You did great on your PR.

**Comment by amjedidiah** [comment]
You're welcome
Thanks for accepting & merging
